version: 2.1

jobs:
   lint-dockerfile:
      docker:
        - image: "docker:18.06.3-ce"
      steps:
        - checkout
        - run:
            name: "Linting Dockerfile"
            command: "docker run --rm -it hadolint/hadolint < Dockerfile"
   test-app:
      docker:
        - image: "cimg/go:1.19.4"
      steps:
        - checkout
        - run:
            name: "Menjalankan unit test untuk backend"
            command: "go test -v -short --count=1 $(go list ./...)"
   build-app-karsajobs:
      docker:
        - image: "docker:18.06.3-ce"
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: "Build Image"
            command: "docker build . -t ghcr.io/yogi-ra/karsajobs:latest"
        - run:
            name: "Login GitHub Packages"
            command: "echo $PASSWORD_GITHUB_PACKAGES | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin"
        - run:
            name: "Push Image"
            command: "docker push ghcr.io/yogi-ra/karsajobs:latest"

workflows:
  lint-dockerfile-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
