version: 2.1

jobs:
   lint-dockerfile:
      docker:
        - image: "docker:docker:18.06.3-ce"
      steps:
        - checkout
        - run:
            name: "Pull image Hadolint"
            command: "docker pull hadolint/hadolint"
        - run:
            name: "Linting Dockerfile"
            command: "docker run --rm -it hadolint/hadolint < Dockerfile"
   test-app:
      docker:
        - image: "golang:1.15-alpine"
      steps:
        - checkout
        - run:
            name: "Menjalankan unit test untuk backend"
            command: "go test -v -short --count=1 $(go list ./...)"
   build-app-karsajobs:
      docker:
        - image: "docker:docker:18.06.3-ce"
          auth:
            username: $CIRCLE_USERNAME
            password: $PASSWORD_GITHUB_PACKAGES
      steps:
        - checkout
        - run:
            name: "Build Image"
            command: "docker build . -t ghcr.io/yogi-ra/karsajobs:latest"
        - run:
            name: "Push Image"
            command: "docker push ghcr.io/yogi-ra/karsajobs:latest"

workflows:
  lint-dockerfile-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
