#Menggunakan CircleCI versi 2.1
version: 2.1

jobs:
   #Job linting Dockerfile
   lint-dockerfile:
      docker:
        #Menggunakan docker image docker:18.06.3-ce
        - image: "docker:18.06.3-ce"
      steps:
        #Checkout branch github
        - checkout
        #Agar dapat menjalankan Docker in Docker (Docker in docker executor)
        - setup_remote_docker
        #Menjalankan hadolint untuk linting Dockerfile
        - run:
            name: "Linting Dockerfile"
            command: "docker run --rm --interactive hadolint/hadolint:latest < Dockerfile"
   #Job build-app-karsajobs-ui
   build-app-karsajobs-ui:
      docker:
        #Menggunakan docker image docker:18.06.3-ce
        - image: "docker:18.06.3-ce"
      steps:
        #Checkout branch github
        - checkout
        #Agar dapat menjalankan Docker in Docker (Docker in docker executor)
        - setup_remote_docker
        #Build image dari Dockerfile
        - run:
            name: "Build Image"
            command: "docker build . -t ghcr.io/yogi-ra/karsajobs-ui:latest"
        #Login GitHub Packages
        - run:
            name: "Login GitHub Packages"
            command: "docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_PASSWORD"
        #Push image ke GitHub Packages
        - run:
            name: "Push Image"
            command: "docker push ghcr.io/yogi-ra/karsajobs-ui:latest"

workflows:
#Workflow lint-dockerfile dan build-app-karsajobs-ui (build & push image)
  lint-build-push-workflow:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui
